site_name: thesis-desi-cmb-fli
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Project Structure: pipeline.md
  - Extending the Skeleton: synthetic.md
  - Data Placeholders: data_access.md
  - Contributing: contributing.md
docs_dir: docs
markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - .
        - docs
      check_paths: true
