site_name: thesis-desi-cmb-fli
theme:
  name: material
nav:
  - Overview: overview.md
  - Pipeline Blueprint: pipeline.md
  - Implementation Roadmap: roadmap.md
  - Data Access Plan: data_access.md
  - NERSC Quickstart: hpc.md
  - Contributing: contributing.md
docs_dir: docs
markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - .
        - docs
      check_paths: true
