site_name: thesis-desi-cmb-fli
theme:
  name: material
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Synthetic demo: synthetic.md
  - Data access: data_access.md
  - Pipeline: pipeline.md
  - Contributing: contributing.md
docs_dir: docs
markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - .
        - docs
      check_paths: true
